# App Info
ios_app_id                                : 949490225                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/us/app/print-to-size/id949490225?uo=4 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://www.dropbox.com/l/lYhyPoEiAOJUlqYCt6vRxq                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/512x512bb.jpg                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Print to Size                             # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : for iPhone and iPad                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The photo printing app that lets you size and crop in centimeters or inches

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Clafou Ltd
your_link                                 : http://www.clafou.com
your_city                                 : Dublin                                
email_address                             : info@clafou.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : clafou
github_username                           : 
youtube_username                          :



# Reviews List
reviews                                   :

  - title                                 : Best for printing
    description                           : This is an awesome app for printing because there is no guess work. You see your page, you add your pic and then you can crop as you see fit. Great for scrapbooking and framing your shots. Before this app, printing pictures from my phone was a nightmare.
    author                                : McWeizer

  - title                                 : Delightful app
    description                           : I love to have the ability to resize photos easily and print out immediately.  Thank you for creating this wonderful app!
    author                                : iammaskier

  - title                                 : Amazing
    description                           : Love how much this app has taken away headache after headache trying to enlarge something. Hats off to Print to size
    author                                : 70s momma

  - title                                 : Perfect!
    description                           : This is exactly what I was looking for for so long! I just wanted to be able to pick my print size (not choose from A4 and such) and position on the page wherever I liked and print multiple photos...as many as I can fit on the page as to not waste paper! I just tried it for the first time and it worked great. Thank you!
    author                                : caalncgirl
    
  - title                                 : Beyond love it! 
    description                           : I’m a professional artist and use this app all day everyday. It is one my most important tools in my tool box ! I have a suggestion that I would use and I think others would love it. Being able to lighten or darken the photos on the spot. Well that’s it and thank you for the absolute most brilliant app!!
    author                                : Mrsfab555

  - title                                 : Love this app!
    description                           : Any Mom with kids doing school projects will absolutely love this app! Saves me a ton of time trying to print pictures the exact size we need!
    author                                : Luv2cook40

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "rgba(191, 48, 105, 0.88)"
cover_overlay_transparency                : 0.8

device_color                              : blue                                      # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "rgb(191, 48, 105)"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "rgb(241, 224, 116)"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
